### ISSUE TITLE
Installation manual

### ISSUE THREAD

**Issue by thundergreen** [jcbrand/inverse.js#2]
Your project sounds awesome and I'd like to implement those in my home automation system for communication purposes. Atm I use kaiwa but for my raspberry it is a bit heavy. Would you mind making a tutorial how to get this page running?

**Comment by jcbrand** [comment]
Thanks.

There already is such a page: https://conversejs.org/docs/html/quickstart.html
And lots of documentation in general: https://conversejs.org/docs/html/index.html
