### ISSUE TITLE
inband pic preview and httpupload

### ISSUE THREAD

**Issue by thundergreen** [jcbrand/inverse.js#3]
I know this project is work in progress, but just want to give thise ideas to make it for me a perfect webchat interface :)

**Comment by jcbrand** [comment]
What do you mean with "inband pic preview"?

If you paste URLs to images in inverse, they will be shown.

**Comment by thundergreen** [comment]
then inversejs has everything i need :) thanks for the reply

2017-02-20 10:35 GMT+01:00 JC Brand <notifications@github.com>:

**Comment by jcbrand** [comment]
Ok, httpupload is handled in converse.js https://github.com/jcbrand/converse.js/issues/161
